### ISSUE TITLE
Decide about using monorepo vs multirepo

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Initiatives/crowdin#16]
It needs to be decided how the core is handled in Crowdin, having either one project with all sys-exts in there or per extension one project.

## Mono-Repo

- Easier to setup & sync

## Multi-Repo

- Easier for translators, especially new ones as there are less files per project

----

With the beta version, the core extensions would get its own workspace, so it wouldn't be a problem regarding usability.

Currently also discussing it with Crowdin if they can split it up later or if we need to do it now

**Comment by liayn** [comment]
I still consider the core as one unit, so I would go with 1 project

**Comment by prathers** [comment]
Agree with mono-repo - Crowdin offers a bunch of filtering tools and views to make it easier for the translators to manoeuvre in files

**Comment by Jivotinka** [comment]
As a new translator I wouldn't mind mono-repo

**Comment by jokumer** [comment]
If mono-repo, what about system extensions which get extracted from TYPO3 CMS core? Like openid, rtehtmlarea, func.
Then it requires a new project like all TER extension.
Does it then exists in two different repos?

**Comment by liayn** [comment]
> 
> 
> If mono-repo, what about system extensions which get extracted from TYPO3 CMS core? Like openid, rtehtmlarea, func.
> Then it requires a new project like all TER extension.
> Does it then exists in two different repos?

I would say yes, that's two different projects then. The code is really duplicated into a dedicated repository so its future might be different, so is the according translation's future.

**Comment by georgringer** [comment]
With upcoming beta of crowdin there will be workspaces to group projects, so next to core could be those extensions like openid

**Comment by georgringer** [comment]
We will stick with mono repo, switching could be done later as well.
Thx for all opinions
