### ISSUE TITLE
XLF: Copy id attribute to attribute resname

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Initiatives/crowdin#19]
Given
```
<trans-unit id="tt_content.asset_references">
	<source>Media elements</source>
</trans-unit>
```

Crowdin doesn't show the information stored in the attribute "id". If we want to have that visible, the attribute must be duplicated using "resname". So it should like that

```
<trans-unit id="tt_content.asset_references" resname="tt_content.asset_references">
	<source>Media elements</source>
</trans-unit>
```

**Comment by liayn** [comment]
search: `(?<!resname=.*)(?!.*resname=)id="([^"]+)"`
replace: `id="$1" resname="$1"`
in all XLF files

**Comment by georgringer** [comment]
@liayn have found a flaw in your regex, IMO must be `(?<!resname=.*)(?!.*resname=) id="([^"]+)"` (mind the space) as there is also something like `<file t3:id`

**Comment by liayn** [comment]
good point. wasn't aware of this. Thanks.

**Comment by liayn** [comment]
https://forge.typo3.org/issues/89335

**Comment by georgringer** [comment]
Solves
