### ISSUE TITLE
Replace attribute "original" with actual file name

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Initiatives/crowdin#25]
A xlf file must provide the property `original` which is currently filled with dummy code "messages".
As this information is shown on Crowdin this should be changed to something more useful. 

Proposal:  Fill it with the path & filename `EXT:about/Resources/Private/Language/Modules/about.xlf`

**Comment by liayn** [comment]
For reference: http://docs.oasis-open.org/xliff/xliff-core/v2.0/xliff-core-v2.0.html#original

**Comment by liayn** [comment]
Moreover this attribute is optional: http://docs.oasis-open.org/xliff/xliff-core/v2.0/xliff-core-v2.0.html#file

**Comment by liayn** [comment]
I'm not sure what the gain is if we repeat the file's name in the attribute again.

**Comment by georgringer** [comment]
See https://crowdin.com/translate/typo3-cms/1234/en-de where messages is placed. And don't forget, we are using version 1.2 where this field is imo requires

**Comment by georgringer** [comment]
solved
