### ISSUE TITLE
Get new server for the translation files

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Initiatives/crowdin#5]
Ask the Server Team for a new server. Requirements:
- rsync
- no PHP or whatsoever needed.

However also check using Azure which is also used for the releases already.

**Comment by liayn** [comment]
What are the tasks this server would have to fulfill?
Would it make sense to craft a docker image for this?

**Comment by georgringer** [comment]
asked at forge https://forge.typo3.org/issues/89218
